name: Markdown check

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
  schedule:
    # run every Monday at 3 AM
    - cron: '0 3 * * 1'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: markdown-lint
      uses: nosborn/github-action-markdown-cli@v3.5.0
      with:
        files: README.md
        config_file: .markdownlint.json
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
        config-file: '.mlc_config.json'
