name: Check Markdown links

on:
  push:
    branches:
		- main
  pull_request:
  schedule:
	# run every Monday at 5 AM
  - cron: "0 5 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
