name: Check Markdown links

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  schedule:
    # run every Monday at 3 AM
    - cron: "0 3 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
