name: Markdown check

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
  schedule:
    # run every Monday at 3 AM
    - cron: '0 3 * * 1'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: markdown-lint
      uses: nosborn/github-action-markdown-cli@508d6cefd8f0cc99eab5d2d4685b1d5f470042c1 # v3.5.0
      with:
        files: README.md
        config_file: .markdownlint.json
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: markdown-link-check
      uses: tcort/github-action-markdown-link-check@e047c5b37f24ab722bbef1a27b6fab7f96bc4068 # v1.1.3
      with:
        use-verbose-mode: 'yes'
        config-file: '.mlc_config.json'
